## test use $seq 1 200 | xargs -n1 -P10  curl -I "http://web-tier-svc.web-tier.svc.cluster.local"
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: circuit-break-vs
  namespace: app-tier
spec:
  hosts:
  - app-tier-svc.app-tier.svc.cluster.local
  http:
  - name: "app-route"  
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: circuit-breaking-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
        http2MaxRequests: 1
      tcp:
        maxConnections: 1
    outlierDetection:
      baseEjectionTime: 3m
      consecutive5xxErrors: 1
      interval: 1ms
      maxEjectionPercent: 100
