---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ext-svc-1
  namespace: test-tier
spec:
  hosts:
  - ec2-15-207-229-119.ap-south-1.compute.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - number: 8181
    name: http-ext-1
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ext-svc-2
  namespace: test-tier
spec:
  hosts:
  - ec2-3-7-183-124.ap-south-1.compute.amazonaws.com
  location: MESH_EXTERNAL
  ports:
  - number: 8181
    name: http-ext-2
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ext-vs
  namespace: test-tier
spec:
  hosts:
  - myapp.com
  http:
  - route:
    - destination:
        host: ec2-15-207-229-119.ap-south-1.compute.amazonaws.com
        port:
          number: 8181
      weight: 100
    mirror:
      host: ec2-3-7-183-124.ap-south-1.compute.amazonaws.com 
      port:
        number: 8181
    mirrorPercentage:
      value: 100.0
