apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rto-vs
  namespace: web-tier
spec:
  hosts:
  - web-tier-svc.web-tier.svc.cluster.local
  http:
  - route:
    - destination:
        host: web-tier-svc.web-tier.svc.cluster.local
    timeout: 1.5s ## Lower to 1s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rto-delay-vs
  namespace: app-tier
spec:
  hosts:
  - app-tier-svc.app-tier.svc.cluster.local
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 1.0s ## Raise to 1.5s
    route:
    - destination:
        host: app-tier-svc.app-tier.svc.cluster.local
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
  namespace: app-tier
spec:
  host: app-tier-svc.app-tier.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
